### ISSUE TITLE
gulp-notify errs thrown when using valid jsx in React 16

### ISSUE THREAD

**Issue by jennifer-shehane** [chrisbreiding/zunder#5]
I'm updating my project to React 16. Updating my `jsx` files to reflect the new React 16 features causes errors to be displayed from zunder.

For example, I am trying to return an array of elements in my `render` method and get this error: 

```sh
[13:10:02] gulp-notify: [Scripts] SyntaxError: .../current-billing.jsx: Adjacent JSX elements must be wrapped in an enclosing tag (21:6)
  19 |           usage={this.props.billing.usage}/>
  20 |       </ErrorBoundary>
> 21 |       <ErrorBoundary key='2'>
     |       ^
  22 |         <BillingDetails
  23 |           onBillingUpdate={this.props.onBillingUpdate}
  24 |           orgId={this.props.org.id}
```

**Comment by chrisbreiding** [comment]
Probably need to bump the react preset for babel. I'll need to make sure that doesn't break projects using React 15 though.

**Comment by chrisbreiding** [comment]
Actually, it doesn't look like the syntax is valid. Adjacent elements need to be in an array, with commas between: https://reactjs.org/blog/2017/09/26/react-v16.0.html

**Comment by jennifer-shehane** [comment]
I totally missed the commas in the docs. CoffeeScript has ruined me.
